export {About } from './About/About'
export {Contact} from './Contact/Contact'
export {Home} from './Home/Home'
export {Projects} from './Projects/Projects'
export {NotFound} from './NotFound/NotFound'
